//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMLTrainer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public byte[] IsPassed { get; set; }
        public string TestId { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
