//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMLTrainer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestVariant
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<int> TestId { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
