//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMLTrainer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UMLTrainerEntities : DbContext
    {
        public UMLTrainerEntities()
            : base("name=UMLTrainerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrow> Arrows { get; set; }
        public virtual DbSet<Diagram> Diagrams { get; set; }
        public virtual DbSet<DiagramType> DiagramTypes { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<Lection> Lections { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<NodeValue> NodeValues { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskElement> TaskElements { get; set; }
        public virtual DbSet<TaskResult> TaskResults { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<TestVariant> TestVariants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
